name: Continuous Integration
on: push
env:
    DB_NAME: inventory_test
    DB_USER: admin
    DB_PASSWORD: admin
jobs:
    run_code_checks:
        runs-on: ubuntu-latest
        steps:
            - name: Setup Postgres
              run: |
                  sudo apt-get install postgresql
                  sudo service postgresql start
                  sudo -u postgres psql -c "CREATE DATABASE ${{env.DB_NAME}};"
                  sudo -u postgres psql -c "CREATE USER ${{env.DB_USER}} WITH PASSWORD ${{env.DB_PASSWORD}} ;"
                  sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE ${{env.DB_NAME}} TO ${{env.DB_USER}};"
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Setup Go
              uses: actions/setup-go@v2
              with:
                  go-version: 1.23.4
            - name: Run linting
              run: |
                  go fmt ./...
                  go vet ./...
            - name: Run tests
              run: |
                  go test ./...
